# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nuoMHLNf_SgLmpcfB-3Xksorpywgv9h
"""

#python code
# Import streamlit for the web app
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nuoMHLNf_SgLmpcfB-3Xksorpywgv9h
"""

# Import streamlit for the web app
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

# Set the page layout to wide
st.set_page_config(layout="wide")

# Custom CSS to adjust title sizes
st.markdown(
    """
    <style>
    .title {
        font-size: 24px;
        font-weight: normal;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Title of the dashboard, centered
st.markdown('<h1 style="text-align: center;">US Senator Portfolio Analysis Dashboard</h1>', unsafe_allow_html=True)

# Creating columns for layout
col1, col2 = st.columns(2)

# Column 1: Table
with col1:
    st.markdown('<p class="title">Overall Senators\' Portfolio Evolution</p>', unsafe_allow_html=True)
    
    # Read CSV data into a dataframe
    url = "https://raw.githubusercontent.com/Laci1004/FIEP/main/DF_Recent_Trades.csv"
    df = pd.read_csv(url).head(500)
    df = df.drop(['ReportDate', 'Amount', 'EstimatedShares', 'EstimatedSharesAdjusted', "House"], axis=1)
    df['PriceChange'] = df['PriceChange'] * 100
    df = df.round({'PriceChange': 1}).reset_index(drop=True)

    # Display the table
    st.dataframe(df, width=500, height=300)

# Column 2: Pie Chart
with col2:
    st.markdown('<p class="title">Overall CO2 Emissions in the US</p>', unsafe_allow_html=True)
    
    # Set Matplotlib backend
    matplotlib.use('Agg')
    
    # Define the data for the pie chart
    senate_holdings = {
        'Company': ['MSFT', 'CVX', 'NVDA', 'TCMD', 'AORT', 'Other'],
        'Value': [5318687.519617519, 145399.90950150584, 1172816.671357914, 
                  138301.38223705292, 131102.6007962471, 643041.4195683461]
    }
    senate_holdings_df = pd.DataFrame(senate_holdings)

    # Plotting the pie chart
    plt.figure(figsize=(4, 4))
    plt.pie(senate_holdings_df['Value'], labels=senate_holdings_df['Company'], autopct='%1.1f%%', startangle=140)
    plt.title('Pie Chart of Company Values')
    st.pyplot()

# Horizontal line
st.markdown('<div style="border-top: 3px solid black; margin-top: 5px;"></div>', unsafe_allow_html=True)

# Additional layout if needed
# ...

# End of the Streamlit application
